#!/usr/bin/env bash
# DNS Privacy Configuration for ubuntu-bootstrap
# Configures DNS over HTTPS (DoH) and DNS over TLS (DoT)
# Uses systemd-resolved for modern Ubuntu systems

set -euo pipefail

# Source logging if available
SCRIPT_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_LIB_DIR/logging.sh" ]]; then
    source "$SCRIPT_LIB_DIR/logging.sh"
else
    log_info() { echo "[INFO] $*"; }
    log_success() { echo "[SUCCESS] $*"; }
    log_warning() { echo "[WARNING] $*"; }
    log_error() { echo "[ERROR] $*" >&2; }
fi

# DNS Provider configurations
declare -A DNS_PROVIDERS=(
    ["cloudflare"]="1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com"
    ["cloudflare-malware"]="1.1.1.2#security.cloudflare-dns.com 1.0.0.2#security.cloudflare-dns.com"
    ["cloudflare-family"]="1.1.1.3#family.cloudflare-dns.com 1.0.0.3#family.cloudflare-dns.com"
    ["google"]="8.8.8.8#dns.google 8.8.4.4#dns.google"
    ["quad9"]="9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net"
    ["quad9-malware"]="9.9.9.11#dns11.quad9.net 149.112.112.11#dns11.quad9.net"
    ["mullvad"]="194.242.2.2#dns.mullvad.net"
    ["nextdns"]="45.90.28.0#dns.nextdns.io 45.90.30.0#dns.nextdns.io"
)

# Check if systemd-resolved is available
is_resolved_available() {
    systemctl is-active --quiet systemd-resolved 2>/dev/null
}

# Get current DNS configuration
get_current_dns() {
    if is_resolved_available; then
        resolvectl status 2>/dev/null | grep -E "DNS Servers|DNS over TLS" | head -5
    else
        cat /etc/resolv.conf 2>/dev/null | grep nameserver
    fi
}

# Show available DNS providers
show_dns_providers() {
    echo ""
    echo "Available DNS Providers with DoT/DoH support:"
    echo ""
    echo "  1) cloudflare        - Cloudflare (1.1.1.1) - Fast, privacy-focused"
    echo "  2) cloudflare-malware - Cloudflare + malware blocking"
    echo "  3) cloudflare-family  - Cloudflare + malware + adult content blocking"
    echo "  4) google            - Google (8.8.8.8) - Reliable, widely used"
    echo "  5) quad9             - Quad9 (9.9.9.9) - Security-focused, blocks threats"
    echo "  6) quad9-malware     - Quad9 + enhanced malware protection"
    echo "  7) mullvad           - Mullvad DNS - Privacy-focused (no logging)"
    echo "  8) nextdns           - NextDNS - Customizable filtering"
    echo ""
}

# Configure DNS over TLS via systemd-resolved
configure_dot() {
    local provider="${1:-cloudflare}"
    local dns_servers="${DNS_PROVIDERS[$provider]:-${DNS_PROVIDERS[cloudflare]}}"

    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "[DRY RUN] Would configure DNS over TLS with provider: $provider"
        log_info "[DRY RUN] DNS servers: $dns_servers"
        return 0
    fi

    if ! is_resolved_available; then
        log_error "systemd-resolved is not running. Cannot configure DoT."
        return 1
    fi

    log_info "Configuring DNS over TLS with provider: $provider"

    # Create resolved.conf.d directory if needed
    sudo mkdir -p /etc/systemd/resolved.conf.d

    # Create DoT configuration
    cat << EOF | sudo tee /etc/systemd/resolved.conf.d/dns-over-tls.conf > /dev/null
# DNS over TLS configuration
# Provider: $provider
# Generated by ubuntu-bootstrap on $(date -Iseconds)

[Resolve]
DNS=$dns_servers
DNSOverTLS=yes
DNSSEC=allow-downgrade
Domains=~.
EOF

    log_info "Restarting systemd-resolved..."
    sudo systemctl restart systemd-resolved

    # Verify configuration
    sleep 2
    if resolvectl status 2>/dev/null | grep -q "DNSOverTLS"; then
        log_success "DNS over TLS configured successfully"
        log_info "Provider: $provider"
        resolvectl status | grep -E "DNS Servers|DNS over TLS" | head -3
        return 0
    else
        log_warning "DNS over TLS may not be fully active"
        return 1
    fi
}

# Disable DNS over TLS (revert to default)
disable_dot() {
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "[DRY RUN] Would remove DNS over TLS configuration"
        return 0
    fi

    if [[ -f /etc/systemd/resolved.conf.d/dns-over-tls.conf ]]; then
        log_info "Removing DNS over TLS configuration..."
        sudo rm -f /etc/systemd/resolved.conf.d/dns-over-tls.conf
        sudo systemctl restart systemd-resolved
        log_success "DNS over TLS disabled, reverted to default DNS"
    else
        log_info "No DoT configuration found"
    fi
}

# Test DNS resolution
test_dns() {
    log_info "Testing DNS resolution..."

    local test_domains=("google.com" "cloudflare.com" "github.com")
    local success=0
    local failed=0

    for domain in "${test_domains[@]}"; do
        if resolvectl query "$domain" >/dev/null 2>&1; then
            log_success "  ✓ $domain resolved"
            ((success++))
        else
            log_error "  ✗ $domain failed"
            ((failed++))
        fi
    done

    echo ""
    log_info "Results: $success passed, $failed failed"

    if (( failed > 0 )); then
        return 1
    fi
    return 0
}

# Interactive DNS setup
interactive_dns_setup() {
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  🔐 DNS Privacy Configuration"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "DNS (Domain Name System) translates website names into IP"
    echo "addresses. By default, these queries are sent unencrypted,"
    echo "allowing your ISP to see every website you visit."
    echo ""
    echo "💡 How DNS over TLS (DoT) Works:"
    echo "   Normal DNS: Your computer → (unencrypted) → ISP → DNS Server"
    echo "   With DoT:   Your computer → (encrypted) → DNS Server"
    echo ""
    echo "   When you type 'github.com', instead of your ISP seeing"
    echo "   this request, it's encrypted end-to-end to your chosen"
    echo "   DNS provider. Your ISP only sees encrypted traffic."
    echo ""
    echo "🛡️  Protection Benefits:"
    echo "   • ISP cannot track which websites you visit"
    echo "   • Prevents DNS spoofing/hijacking attacks"
    echo "   • Blocks man-in-the-middle DNS manipulation"
    echo "   • Complements VPN for comprehensive privacy"
    echo ""

    show_dns_providers

    echo "Options:"
    echo "  1-8) Select a DNS provider"
    echo "  d)   Disable DoT (use default DNS)"
    echo "  t)   Test current DNS configuration"
    echo "  s)   Show current DNS status"
    echo "  q)   Quit without changes"
    echo ""

    read -p "Enter choice: " choice

    case "$choice" in
        1) configure_dot "cloudflare" ;;
        2) configure_dot "cloudflare-malware" ;;
        3) configure_dot "cloudflare-family" ;;
        4) configure_dot "google" ;;
        5) configure_dot "quad9" ;;
        6) configure_dot "quad9-malware" ;;
        7) configure_dot "mullvad" ;;
        8) configure_dot "nextdns" ;;
        d|D) disable_dot ;;
        t|T) test_dns ;;
        s|S) get_current_dns ;;
        q|Q) log_info "No changes made" ;;
        *) log_error "Invalid choice" ;;
    esac
}

# Main entry point when run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        --configure)
            configure_dot "${2:-cloudflare}"
            ;;
        --disable)
            disable_dot
            ;;
        --test)
            test_dns
            ;;
        --status)
            get_current_dns
            ;;
        --providers)
            show_dns_providers
            ;;
        --interactive|-i)
            interactive_dns_setup
            ;;
        --help|-h)
            echo "DNS Privacy Configuration for ubuntu-bootstrap"
            echo ""
            echo "Usage: $0 [OPTION]"
            echo ""
            echo "Options:"
            echo "  --configure [provider]  Configure DNS over TLS (default: cloudflare)"
            echo "  --disable               Disable DoT, revert to default DNS"
            echo "  --test                  Test DNS resolution"
            echo "  --status                Show current DNS configuration"
            echo "  --providers             List available DNS providers"
            echo "  --interactive, -i       Interactive setup wizard"
            echo "  --help, -h              Show this help"
            echo ""
            echo "Providers: cloudflare, cloudflare-malware, cloudflare-family,"
            echo "           google, quad9, quad9-malware, mullvad, nextdns"
            ;;
        *)
            interactive_dns_setup
            ;;
    esac
fi
