name: verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run verify
        run: |
          set -euo pipefail
          # Canonical verify entrypoint (wrapper -> 99_verify.sh)
          if [ -f "./scripts/verify.sh" ]; then
            echo "[i] Running scripts/verify.sh"
            bash ./scripts/verify.sh
          else
            echo "[!] scripts/verify.sh missing; skipping"
          fi
